name: CD ClientService Localstack Demo

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

env:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: sa-east-1
  IMAGE_NAME: clientservice
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15-alpine
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: client_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build application image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Prepare .env for container
        run: |
          cat > .env << 'EOF'
          DB_HOST=db
          DB_PORT=5432
          DB_USER=postgres
          DB_PASSWORD=mysecretpassword
          DB_NAME=client_db
          SECRET_KEY=your_secret_key
          ALGORITHM=HS256
          ACCESS_TOKEN_EXPIRE_MINUTES=30
          DD_API_KEY=${{ secrets.DD_API_KEY }}
          EOF
          sed -n '1,20p' .env

      - name: Create external network (video-net)
        run: |
          docker network create video-net || true
          docker network ls

      - name: Run migrations
        run: |
          docker run --rm \
            --network video-net \
            --env-file .env \
            -v ${{ github.workspace }}:/app \
            -w /app \
            $IMAGE_NAME:$IMAGE_TAG \
            alembic upgrade head

      - name: Launch app
        run: |
          docker run -d --name clientservice-web \
            --network video-net \
            --env-file .env \
            -p 8004:8000 \
            $IMAGE_NAME:$IMAGE_TAG \
            uvicorn main:app --host 0.0.0.0 --port 8000

      - name: Health check (HTTP)
        run: |
          set -e
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8004/docs || true)
            if [ "$code" = "200" ]; then
              echo "clientservice UP (/docs 200)"; exit 0
            fi
            echo "Aguardando app... código=$code"; sleep 2
          done
          docker logs clientservice-web; exit 1

      - name: Export logs
        run: |
          docker logs clientservice-web > clientservice.log || true

      - name: Upload run logs
        uses: actions/upload-artifact@v4
        with:
          name: cd-clientservice-logs
          path: clientservice.log
